FILE_LOG_FORMAT = '%(asctime)s~%(levelname)s~  %(message)s  ~module:%(module)s~function:%(module)s'
CONSOLE_LOG_FORMAT = '%(levelname)s -- %(message)s'
OPERATION_ERROR_MESSAGE = "Error in line: {line_num}. Operation {OP} requires exactly {n} argument(s)."
BEGIN = "begin"
BEGIN_RO = "beginRO"
W = "W"
R = "R"
RECOVER = "recover"
FAIL = "fail"
DUMP = "dump"
END = "end"
